name: '@epistemology-factory/crocks-ext'

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

permissions:
  contents: write

env:
  bot_username: github-actions
  bot_email: github-actions@github.com

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: benjlevesque/short-sha@v2.1
        id: short-sha
        with:
          length: 7

      - name: Git setup
        run: |
          git config user.name ${{ env.bot_username }}
          git config user.email ${{ env.bot_email }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: https://registry.npmjs.org/
          cache: 'npm'

      - name: NPM install
        run: npm install

      - name: NPM Build
        run: npm run dist:build

      - name: Commit formatting changes
        run: |
          git add src/ test/ || echo "No changes to stage"
          git commit -m 'Formatting changes' || echo "No changes to commit"
          git push

      - name: Cache
        uses: actions/cache@v3
        with:
          key: build-${{ env.SHA }}
          path: "build"

  publish:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [ build ]
    steps:
      - uses: benjlevesque/short-sha@v2.1
        id: short-sha
        with:
          length: 7

      - name: Restore Cache
        uses: actions/cache@v3
        with:
          key: build-${{ env.SHA }}
          path: "build"
          fail-on-cache-miss: true

      - name: Repackage
        run: |
          mv build/* .
          rmdir build

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: https://registry.npmjs.org/
          cache: 'npm'

      - name: Publish
        id: publish
        uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_TOKEN }}

  release:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [ publish ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Tag
        id: tag
        uses: kierans/gh-action-tag-on-npm-version@master
        with:
          git-user-name: ${{ env.bot_username }}
          git-user-email: ${{ env.bot_email }}

      - name: Release
        if: ${{ steps.tag.outputs.tag-created == 'true' }}
        uses: softprops/action-gh-release@v1
        with:
          prerelease: false
